config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
  resources :messages
 end
 
  resources :friendships
  delete '/logout' => 'sessions#destroy'
  get '/unread' => 'conversations#unread'
  get '/all' => 'conversations#all'
  resources :sessions , only: [:new, :create]
  resources :users
  root  'home#index'
  

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
      where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.recipient_id = ? AND conversations.sender_id = ?)", sender_id,recipient_id, recipient_id, sender_id)
    end
    
    scope :for, -> (user_id) do
      where("conversations.sender_id = ? OR conversations.recipient_id = ?", user_id, user_id)
    end



end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
   before_action :authenticate_user
   after_action :update_read, only: [:unread]
   

  def index
   @users = User.where.not(id: current_user.id)
   @conversations = Conversation.for(current_user.id)
  end

  def create

    if Conversation.between(params[:sender_id],params[:recipient_id])
     .present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
   else
    @conversation = Conversation.create!(conversation_params)
   end
   redirect_to conversation_messages_path(@conversation)
  end


  def all

    @users = User.where.not(id: current_user.id)
   @conversations = Conversation.for(current_user.id)
   
  end
  
  def unread
   @users = User.where.not(id: current_user.id)
   @conversations = Conversation.for(current_user.id)
  end


  private 
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def update_read
    Message.joins(:conversation).where(read: false, read_at: nil).where(conversations: {id: @conversations.pluck(:id)}).update(read: true, read_at: Time.now)
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/all.html.erb
<div class="ui segment">
    <div class="col-md-6">  
     <h3>Mailbox</h3>
           <div class="ui list">
              <% @conversations.each do |conversation| %>
                <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
                <% if conversation.sender_id == current_user.id %>
                  <% recipient = User.find(conversation.recipient_id) %>
                <% else %>
                  <% recipient = User.find(conversation.sender_id) %>
                <% end %>
                
                            <table class="table">
                              <thead class="thead thead-default">
                                <tr>
                                  <th>Name</th>
                                  <th>Content</th>
                                </tr>
                              </thead>
                            
                                <%  conversation.messages.where.not(read_at: nil).each do  |message| %>
                                  <tr>
                                    <td><%= link_to recipient.name, conversation_messages_path(conversation)%></td>
                                    
                                      <td><i><b><%= link_to message.body, conversation_messages_path(conversation)  %></b></i></td>
                                    
                                  </tr>
                                
                                <% end %> 
                              </tbody>
                          </table>
               
             <% end %>
            <% end %>
            
           </div>
    </div>
</div>

app/views/conversations/create.html.erb
<h1>Conversations#create</h1>
<p>Find me in app/views/conversations/create.html.erb</p>

app/views/conversations/index.html.erb
<div class="ui segment">
               <ul>
                   <li><%= link_to "unread message",unread_path  %></li>
  
                   <li><%= link_to " read message", all_path %> </li>
              </ul>

 </div> 

<div class="ui segment">
 <h3>All Users</h3>
  <div class="ui list">
   <% @users.each do |user| %>
<% if current_user.is_friend?(user) %>
    <% if user.id != current_user.id %>
     <div class="item">

   <%= user.name %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
 </div>
  <% end %>
 <% end %>
 <% end %>
 </div>
</div>

app/views/conversations/unread.html.erb
<div class="ui segment">
    <div class="col-md-6">  
     <h3>Mailbox</h3>
           <div class="ui list">
              <% @conversations.each do |conversation| %>
                <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
                <% if conversation.sender_id == current_user.id %>
                  <% recipient = User.find(conversation.recipient_id) %>
                <% else %>
                  <% recipient = User.find(conversation.sender_id) %>
                <% end %>
                
                            <table class="table">
                              <thead class="thead thead-default">
                                <tr>
                                  <th>Name</th>
                                  <th>Content</th>
                                </tr>
                              </thead>
                            
                                <%  conversation.messages.where(read_at: nil).each do  |message| %>
                                  <tr>
                                    <td><%= link_to recipient.name, conversation_messages_path(conversation)%></td>
                                    
                                      <td><i><b><%= link_to message.body, conversation_messages_path(conversation)  %></b></i></td>
                                    
                                  </tr>
                                
                                <% end %> 
                              </tbody>
                          </table>
               
             <% end %>
            <% end %>
            
           </div>
    </div>
</div>