config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
  resources :messages
 end
 
  resources :friendships
  delete '/logout' => 'sessions#destroy'
  get '/unread' => 'conversations#unread'
  get '/all' => 'conversations#all'
  resources :sessions , only: [:new, :create]
  resources :users
  root  'home#index'
  

end

app/models/user.rb
class User < ApplicationRecord
validates :email, uniqueness: true
validates :name, presence: true
has_many :friendships
has_many :friends, :through => :friendships
has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
has_many :inverse_friends, :through => :inverse_friendships, :source => :user
validates :name, presence: true
validates :email, presence: true, uniqueness: {case_insensitive: false}
validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
has_secure_password


    def incoming_messages
      Message.where(recipient_id: id).order('created_at DESC')
    end

    def last_online
      self.created_at = Time.now
    end

  def is_friend?(user)
    self.friend_ids.include?(user.id)
  end

  def sent_messages
    Message.where(sender_id: id).oreder('created_at DESC')
    end
end

app/controllers/users_controller.rb
    class UsersController < ApplicationController

  def index
  Rails.logger.info request.env["HTTP_COOKIE"]
    @users = User.all
    @users = User.where.not(id: current_user.id)
  end

  def new
    @user = User.new
  end
  def show 
    @friendships = Friendship.all
    @users = User.all

  end 
  def create 
    @user=User.create user_params
    if @user.persisted?
      session[:user_id]= @user.id
      flash[:success]= "registed successfully"
      redirect_to root_path

    else
      flash[:error]= "Error: #{@user.errors.full_messages}"
      render 'new'
    end
  end

 def sent_message
    @current_user_conversations = Conversation.where('sender_id = ?',current_user.id)
    @sent_messages = []
    @current_user_conversations.each do |current_user_conversation|
      current_user_conversation.messages.each do |message|
        @sent_messages << message
      end
    end
  end

    # def group_message
    #   before_action :authenticate_user
    #   query = params[:search]
    #   @users = current_user.friendships(params[:friend_id]).where("user.name LIKE ? OR user.email LIKE ? " ,"%#{query}%").excludes(:id=> current_user.id)
    #   @message = @conversation.messages.new
    # end
 

  private 
  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def flash_class_name(key)
  case key.to_s
  when :success
    "alert-success"
  when :error
    "alert-danger"
  else
    "alert-warning"
  end
  end
end

app/views/users/_index.html.erb
<h1> Find Friends </h1>

<table class="table">
  <thead class="thead thead-default">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Created At</th>
      
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.name%></td>
          <td><%= user.email %></td>
          
          <td><%= time_ago_in_words user.created_at%></td>

          <td>
            <%= link_to "Add Friend", friendships_path(:user_id => user), :method => :post, class: "btn btn-primary" %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/users/group_message.html.erb
<%= @users.each do |f| %>
<%= user.email %>

app/views/users/new.html.erb
<div class="container">
<h1>Create An Account</h1>


<%= form_for @user do |f| %>
<% unless @user.errors.empty? %>
  <div class="alert alert-danger">
    <%= @user.errors.full_messages.to_sentence %>
  </div>
<% end %>
<div class="form-group" %>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Enter Your Name", class: "form-control" %>
  </div>


  <div class="form-group" %>
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: "Enter Your Email", class: "form-control" %>
  </div>

  <div class="form-group" %>
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: "Enter Your Password", class: "form-control" %>
  </div>

  <div class="form-group" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, placeholder: "Re-Enter Your Password", class: "form-control" %>
  </div>

  <%= f.submit "Create An Account", class: "btn btn-info" %>
<% end %>
</div>

app/views/users/sent_message.html.erb
<h1> Sent Messages </h1>
<% @sent_messages.each do |sent_message| %>
<br>
 <%= 'Receipient:' + User.find_by_id(sent_message.conversation.recipient_id).name %>
 <br>
 <strong><%= sent_message.body %></strong>
 <br>
 <%= time_ago_in_words sent_message.created_at %>
 <br/>  
<% end %>

app/views/users/show.html.erb
<h2>Friends List</h2>

<table class="table">
  <thead class="thead thead-default">
    <tr>
      <th>Friend Name</th>
      <th>Email</th>
      <th>Created At</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
     <% @friendships.each do |friendship|  %>
        <tr>
          <td><%= friendship.friend.name %></td>
          <td><%= friendship.friend.email %></td>
          <td><%= time_ago_in_words friendship.friend.created_at %></td>
          <td>
            <%= link_to "remove", friendship, :method => :delete, class: "btn btn-danger" %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>
<ul>
<p><%= link_to "Find Friends", users_path, class: 'btn btn-default' %></p>