config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
  resources :messages
 end
 
  resources :friendships
  delete '/logout' => 'sessions#destroy'
  get '/unread' => 'conversations#unread'
  get '/all' => 'conversations#all'
  resources :sessions , only: [:new, :create]
  resources :users
  root  'home#index'
  

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User"

  # def accept_friend!
  #   self.acceptance = true
  # end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
   @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = current_user.friendships.build
    @friendship.friend_id = params[:user_id]
    @friendship.user_id = current_user.id
    if @friendship.save!
      flash[:notice] = "Added friend."
      redirect_to friendships_path
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update

    # @friendship = Friendship.find(params[:id])
    # @friendship.accept_friend!
    # redirect_to friendships_path
   respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
def destroy
  @friendship = current_user.friendships.find(params[:id])
  @friendship.destroy
  flash[:notice] = "Removed friendship."
  redirect_to friendships_path(current_user)
end

  private
     def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :create, :destroy)
    end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(friendship) do |f| %>
  <% if friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :friend_id %>
    <%= f.number_field :friend_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h2>Friends List</h2>
<table class="table">
  <thead class="thead thead-default">
    <tr>
      <th>Friend Name</th>
      <th>Email</th>
      <th>Created At</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
     <% @friendships.each do |friendship|  %>
        <tr>
          <td><%= friendship.friend.name %></td>
          <td><%= friendship.friend.email %></td>
          <td><%= time_ago_in_words friendship.friend.created_at %></td>
          <td>
          <%= link_to "remove", friendship_path(friendship.id), :method => :delete, class: "btn btn-danger" %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>
<ul>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Create:</strong>
  <%= @friendship.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @friendship.destroy %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>