config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
  resources :messages
 end
 
  resources :friendships
  delete '/logout' => 'sessions#destroy'
  get '/unread' => 'conversations#unread'
  get '/all' => 'conversations#all'
  resources :sessions , only: [:new, :create]
  resources :users
  root  'home#index'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homew2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
 
  <% if current_user %>
       <div class ="alert alert-info">
          Welcome <%= current_user.name %>
          <%= link_to "Log Out " ,logout_path ,method: 'delete'  %>
          <%= link_to 'View Friends', friendships_path(current_user) %>
          <%= link_to "mailbox", conversations_path %>
       </div>
  <% else %>
         
           <%= link_to 'new Account', new_user_path, class: 'nav-link' %>
          <%= link_to "Log in", new_session_path %>
  <% end %>

        <% if flash.any? %>
              <% flash.each do |key, value| %>
                  <div class="alert <%=
                   flash_class_name(key) %> " >
                  <%= value %>
                  </div>
                <% end %>
        <% end %>
    <div class="container">
        <%= yield %>
        <%= debug(params) if Rails.env.development? %> 
    </div>
  </body>
</html>